#+TITLE: Guix Stack

* Guix Stack

This repository is home of the =guix-stack= channel and extension.

The goal is to provide tools to help for local guix development.
It's still mostly undocumented.

The channel provides an extension of =guix pull=.

It builds upon =guix= and =guix-local=.
This channel won't work on upstream guix.  It currently requires patchset 68315 to work properly.

** Available subcommands

Current available subcommands are :
- =guix stack pull= to pull from a channel patched with a list of
  deterministic file-likes.
  This has a bug currently.

** Implementation notes

In the development phase, this repository had a =guix stack
install-hook= command, that installed a git hook that recorded metadata
when emails are sent with =git send-email=.  It was discontinued because
configuration-wise, it started to get tricky:
- =sendemail-validate= was not precise enough (patches actually sent after validation had a different/later message-ID)
- so the only option was to patch =sendemail=
  - but that makes configuration tricky: reading =sendemail.sendemail=, replacing it but making a proper backup...
  - I could've used the yoctocell's =direnv= trick, but that introduces a new dependency...

All in all, it s sounded much more adapted to an Emacs workflow (more flexible hooks, callbacks...) than a pure git one.
The part implementing those ideas has been moved to the =git-email= package.

** Documentation for Guix Extensions

- guix extensions are now supported within channels since 74633

** More ideas

- use a git stash in order to save the contents of the configuration.
  That might be better than using a guix-configured.stamp file.
  That would require to implement the git-stash part from libgit2 in guile-git.
